//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFWUnity.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    [DB(DbName = DbName.MyFWUnityBasicDB)]
    public partial class B_EmailMessage
    {
        public string ID { get; set; }
        public string SendTo { get; set; }
        public string CC { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Attachments { get; set; }
        public string ReceiveUsers { get; set; }
        public string CCUsers { get; set; }
        public bool IsBodyHTML { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
