//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFWUnity.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    [DB(DbName = DbName.MyFWUnityBasicDB)]
    public partial class B_Log
    {
        public string ID { get; set; }
        public string ModulePage { get; set; }
        public string Description { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
